# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
#gem "jekyll"
gem 'jemoji'
gem 'webrick'

# gem "rails"
gem "github-pages", "219", group: :jekyll_plugins
